### ISSUE TITLE
Install fails: mising clap-api/README.markdown in 0.12.0

### ISSUE THREAD

**Issue by Flashwalker** [marekjm/clap#2]
Looks like somebody miss the README  
installation fails with:  
```
Downloading https://files.pythonhosted.org/packages/c4/57/d4a2f5b6161c371606eeb136dab27af40f66764a488187ebd27bca329f1b/clap-api-0.12.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-install-afo9fht5/clap-api/setup.py", line 17, in <module>
        with open(path.join(here, 'README.markdown'), encoding='utf-8') as f:
      File "/data/data/com.termux/files/usr/lib/python3.7/codecs.py", line 898, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/usr/tmp/pip-install-afo9fht5/clap-api/README.markdown'
```

**Comment by marekjm** [comment]
Ooops... thanks for finding that.

**Comment by Flashwalker** [comment]
@marekjm  you forgot to update in pipy.org
